### Constants
@host = 192.168.1.8
@user = admin
@password = admin
@port = 8111

### Hardcoded data
@projectId = project1
@buildTypeId = buildType1

### Get all projects
GET http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json

### Step 1: create project
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/projects
Content-Type: application/json
Accept: application/json

{
  "parentProject": {
    "locator": "_Root"
  },
  "name": "{{projectId}}",
  "id": "{{projectId}}",
  "copyAllAssociatedSettings": true
}

### Step 2: create build type
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildTypes
Content-Type: application/json
Accept: application/json

{
  "id": "{{buildTypeId}}",
  "name": "{{buildTypeId}}",
  "project": {
    "id": "{{projectId}}"
  },
  "parameters": {
    "property": [
      {
        "name": "myBuildParameter",
        "value": "myValue"
      }
    ]
  },
  "steps": {
    "step": [
      {
        "name": "myCommandLineStep",
        "type": "simpleRunner",
        "properties": {
          "property": [
            {
              "name": "script.content",
              "value": "echo 'Hello World!'"
            }
          ]
        }
      }
    ]
  }
}

### Step 3: run build
# @no-cookie-jar
POST http://{{user}}:{{password}}@{{host}}:{{port}}/app/rest/buildQueue
Content-Type: application/json
Accept: application/json

{
	"buildType": {
    	"id": "{{buildTypeId}}"
	}
}